version: '3'

services:
  dwin-lcd:
    build: .
    container_name: prind-dwin-lcd
    environment:
      - ENCODER_PINS=26,19
      - BUTTON_PIN=13
      - LCD_COM_PORT=/dev/ttyAMA0
      - API_KEY=USE_IF_NEEDED
      - KLIPPY_SOCKET=/opt/printer_data/run/klipper.sock
      - URL=127.0.0.1
    depends_on:
      klipper:
        condition: service_started
    devices:
      - /dev:/dev
    volumes:
      - run:/opt/printer_data/run
    restart: always 