version: '3'

services:
  dwin-lcd:
    build: .
    container_name: dwin-lcd
    environment:
      - ENCODER_PINS=26,19
      - BUTTON_PIN=13
      - LCD_COM_PORT=/dev/ttyAMA0
      - API_KEY=USE_IF_NEEDED
      - KLIPPY_SOCKET=/opt/printer_data/run/klipper.sock
      - URL=127.0.0.1
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
    volumes:
      - run:/opt/printer_data/run
    restart: unless-stopped 